server:
  port: 8085
minio:
  endpoint: ${MINIO_SERVER_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:internship}
  secretKey: ${MINIO_SECRET_KEY:internship2024}
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:internship}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:InternshipUCB}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:InternshipUCB}/protocol/openid-connect/certs
keycloak:
  url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
token:
  converter:
    principal-attribute: preferred_username
    resource-id: ${KEYCLOAK_CLIENT_ID:internship_cliente}

environment:
  frontend_url: ${FRONTEND_URL:http://localhost:5173}

#Configuraciones de seguridad
security-constraints:
  constraints:
    #Example of security constraints
    - auth-roles:
        #list of roles that can access this endpoint
        - ESTUDIANTE
        - ADMIN
      security-collections:
        - name: student
          patterns:
            # list of endpoints that require the roles specified above
            - /test/student
            - /test/student/*
            - /test/student/**
          methods:
            # list of methods that can access the endpoint
            - GET

    - auth-roles:
        - EMPRESA
      security-collections:
        - name: business
          patterns:
            - /test/business
          methods:
            - GET

    - auth-roles:
        - ADMIN
      security-collections:
        - name: admin
          patterns:
            - /test/admin
          methods:
            - GET

    - auth-roles:
        - permitAll
      security-collections:
        - name: public
          patterns:
            - /api/v1/usuario
          methods:
            - POST


