server:
  port: 8085
minio:
  endpoint: ${MINIO_SERVER_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:internship}
  secretKey: ${MINIO_SECRET_KEY:internship2024}
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:internship}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:InternshipUCB}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:InternshipUCB}/protocol/openid-connect/certs
keycloak:
  url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
token:
  converter:
    principal-attribute: preferred_username
    resource-id: ${KEYCLOAK_CLIENT_ID:internship_cliente}

environment:
  frontend_url: ${FRONTEND_URL:http://localhost:5173}

#Configuraciones de seguridad
security-constraints:
  constraints:
    #Example of security constraints
    - auth-roles:
        #list of roles that can access this endpoint
        - EMPRESA
      security-collections:
        - name: empresa put methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario/*/pasantia/*
            - /api/v1/usuario/*/institucion/*
            - /api/v1/institucion/usuario/*
          methods:
            # list of methods that can access the endpoint
            - PUT

    #Example of security constraints
    - auth-roles:
        #list of roles that can access this endpoint
        - EMPRESA
      security-collections:
        - name: empresa post methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario/*/institucion
            - /api/v1/usuario/*/institucion/*
          methods:
            # list of methods that can access the endpoint
            - POST

    - auth-roles:
        #list of roles that can access this endpoint
        - EMPRESA
      security-collections:
        - name: empresa get methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario/*/institucion
            - /api/v1/institucion/usuario/*
          methods:
            # list of methods that can access the endpoint
            - GET

    - auth-roles:
        #list of roles that can access this endpoint
        - EMPRESA
      security-collections:
        - name: empresa delete methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario/*/institucion/*
            - /api/v1/usuario/*/pasantia/*
          methods:
            # list of methods that can access the endpoint
            - DELETE

    - auth-roles:
        #list of roles that can access this endpoint
        - authenticated
      security-collections:
        - name: authenticated post methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario
            - /api/v1/usuario/institucion
            - /api/v1/usuario/persona
          methods:
            # list of methods that can access the endpoint
            - POST

    - auth-roles:
        #list of roles that can access this endpoint
        - authenticated
      security-collections:
        - name: authenticated post methods
          patterns:
            # list of endpoints that require the roles specified above
            - /api/v1/usuario/*/pasantia/*/detalle #Verificar
            - /api/v1/usuario/*/institucion/*/pasantias #Verificar
          methods:
            # list of methods that can access the endpoint
            - GET

#    - auth-roles:
#        -permitAll
#      security-collections:
#        - name: permitAll get methods
#          patterns:
#            - /api/v1/usuario/*/empresa/aprobado
#            - /api/v1/institucion
#            - /api/v1/institucion/destacadas
#            - /api/v1/institucion/nombre
#            - /api/v1/institucion/sectores
#            - /api/v1/institucion/*/relacionadas
#          methods:
#            - GET


